# Removed deprecated source.
[tool.poetry.dependencies]
python = ">3.7,<4"
mechanize = "*"
selenium = "*"
mechanicalsoup = "*"
fastapi = "^0.100.0"
uvicorn = {extras = ["standard"], version = "^0.22.0"}

# Changed line below because the old version was deprecated.
[tool.poetry.group.dev.dependencies]
black = "^22.6.0"

[tool.poetry]
name = "handelsregister"
version = "0.2.1"
description = "Adapted fork of the BundesAPI Handelsregister repo."
authors = ["BundesAPI <kontakt@bund.dev>"]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.tox]
legacy_tox_ini = """
[tox]
envlist = py36,py37,py38,py310
isolated_build = True

[tox:.package]
basepython = python3

[testenv]
deps = pytest
usedevelop = true
commands =
    pytest
"""
